// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Provet.Infrastructure.Configuration;

#nullable disable

namespace Provet.Infrastructure.Migrations
{
    [DbContext(typeof(ContextBase))]
    [Migration("20230411120539_UpdateTableUsuario")]
    partial class UpdateTableUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Provet.Entities.Entities.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PERF_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("PERF_ATUALIZADO_EM");

                    b.Property<bool>("Atualizar")
                        .HasColumnType("boolean")
                        .HasColumnName("PERF_ATUALIZAR");

                    b.Property<bool>("Consultar")
                        .HasColumnType("boolean")
                        .HasColumnName("PERF_CONSULTAR");

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("PERF_CRIADO_EM");

                    b.Property<bool>("Deletar")
                        .HasColumnType("boolean")
                        .HasColumnName("PERF_DELETAR");

                    b.Property<bool>("Inserir")
                        .HasColumnType("boolean")
                        .HasColumnName("PERF_INSERIR");

                    b.Property<bool>("Listar")
                        .HasColumnType("boolean")
                        .HasColumnName("PERF_LISTAR");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("PERF_NOME");

                    b.HasKey("Id");

                    b.ToTable("TB_PERFIL");
                });

            modelBuilder.Entity("Provet.Entities.Entities.Responsavel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("RESP_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("RESP_ATUALIZADO_EM");

                    b.Property<string>("Bairro")
                        .HasColumnType("text")
                        .HasColumnName("RESP_BAIRRO");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("RESP_CELULAR");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("RESP_CEP");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("RESP_CIDADE");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("RESP_CPF");

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("RESP_CRIADO_EM");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("RESP_DATA_NASCIMENTO");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("RESP_EMAIL");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("RESP_ENDERECO");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("RESP_ESTADO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("RESP_NOME");

                    b.Property<string>("Numero")
                        .HasColumnType("text")
                        .HasColumnName("RESP_NUMERO");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("RESP_OBERVACAO");

                    b.Property<string>("Rg")
                        .HasColumnType("text")
                        .HasColumnName("RESP_RG");

                    b.Property<string>("Telefone")
                        .HasColumnType("text")
                        .HasColumnName("RESP_TELEFONE");

                    b.HasKey("Id");

                    b.ToTable("TB_RESPONSAVEL");
                });

            modelBuilder.Entity("Provet.Entities.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("USU_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("USU_ATUALIZADO_EM");

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("USU_CRIADO_EM");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("USU_NOME");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("USU_USUARIO");

                    b.Property<int>("PerfilId")
                        .HasColumnType("integer");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("USU_SENHA");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.ToTable("TB_USUARIO");
                });

            modelBuilder.Entity("Provet.Entities.Entities.Usuario", b =>
                {
                    b.HasOne("Provet.Entities.Entities.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");
                });
#pragma warning restore 612, 618
        }
    }
}
